# Generated by Django 3.0.5 on 2020-05-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0004_auto_20200508_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='economy_metric',
        ),
    ]
