# Generated by Django 3.0.5 on 2020-05-11 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbontax', '0005_remove_vehicle_economy_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioninstance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emissioninstance',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
