# Generated by Django 3.0.5 on 2020-05-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0006_auto_20200511_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissioninstance',
            name='user',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
