# Generated by Django 3.0.5 on 2020-05-12 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbontax', '0008_auto_20200512_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.ForeignKey(help_text='Select a fuel type for this vehicle.', on_delete=django.db.models.deletion.CASCADE, to='carbontax.FuelType'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
