# Generated by Django 3.0.5 on 2020-05-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0009_auto_20200512_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(max_length=30),
        ),
    ]
