# Generated by Django 3.0.5 on 2020-05-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0010_auto_20200512_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.ForeignKey(help_text='Select a fuel type for this vehicle.', on_delete=django.db.models.deletion.CASCADE, to='carbontax.FuelType'),
        ),
    ]
