# Generated by Django 3.0.5 on 2020-05-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0012_auto_20200515_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissioninstance',
            name='user',
        ),
    ]
