# Generated by Django 3.0.5 on 2020-05-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0016_taxrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxrate',
            old_name='pricePerKg',
            new_name='price_per_kg',
        ),
        migrations.AddField(
            model_name='profile',
            name='taxes',
            field=models.ManyToManyField(null=True, to='carbontax.TaxRate'),
        ),
    ]
