# Generated by Django 3.0.5 on 2020-05-21 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbontax', '0019_auto_20200521_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
