# Generated by Django 3.0.5 on 2020-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0020_auto_20200521_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='taxes',
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
