# Generated by Django 3.0.5 on 2020-05-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0021_auto_20200521_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='price_per_kg',
            field=models.FloatField(default=0),
        ),
    ]
