# Generated by Django 3.0.5 on 2020-05-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0022_auto_20200521_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['price_per_kg']},
        ),
    ]
