# Generated by Django 3.0.5 on 2020-05-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0025_auto_20200526_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together=set(),
        ),
    ]
