# Generated by Django 3.0.5 on 2020-05-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0028_auto_20200528_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissioninstance',
            options={'ordering': ['-date', 'distance']},
        ),
    ]
