# Generated by Django 3.0.5 on 2020-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0030_auto_20200528_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
