# Generated by Django 3.0.5 on 2020-06-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0033_auto_20200531_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['id']},
        ),
    ]
