# Generated by Django 3.0.5 on 2020-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0034_auto_20200602_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['category', 'usage', 'id']},
        ),
        migrations.AddField(
            model_name='taxrate',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
