# Generated by Django 3.0.5 on 2020-06-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0035_auto_20200602_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['category', '-usage', 'id']},
        ),
    ]
