# Generated by Django 3.0.5 on 2020-06-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0037_auto_20200604_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(default='AUD', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_units',
            field=models.CharField(default='lPer100Km', max_length=10),
        ),
    ]
