# Generated by Django 3.0.5 on 2020-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0038_auto_20200606_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='conversion_factor',
            field=models.FloatField(default=1),
        ),
    ]
