# Generated by Django 3.0.5 on 2020-06-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0039_profile_conversion_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60, null=True)),
                ('website', models.URLField(max_length=100, null=True)),
                ('donation_link', models.URLField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='emissioninstance',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(null=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='carbontax.DonationRecipient')),
            ],
        ),
        migrations.AddField(
            model_name='emissioninstance',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emissions', to='carbontax.Payment'),
        ),
    ]
