# Generated by Django 3.0.5 on 2020-06-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0041_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
