# Generated by Django 3.0.5 on 2020-06-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0043_remove_emissioninstance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioninstance',
            name='split',
            field=models.FloatField(default=1),
        ),
    ]
