# Generated by Django 3.0.5 on 2020-06-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0044_emissioninstance_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioninstance',
            name='economy',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='emissioninstance',
            name='fuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='carbontax.FuelType'),
        ),
        migrations.AlterField(
            model_name='emissioninstance',
            name='tax_type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
