# Generated by Django 3.0.5 on 2020-06-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0046_remove_emissioninstance_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioninstance',
            name='tax_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emissions', to='carbontax.TaxRate'),
        ),
    ]
