# Generated by Django 3.0.5 on 2020-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0047_emissioninstance_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recipients',
            field=models.ManyToManyField(null=True, related_name='users', to='carbontax.DonationRecipient'),
        ),
    ]
