# Generated by Django 3.0.5 on 2020-07-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0048_profile_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrecipient',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.AlterField(
            model_name='profile',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='users', to='carbontax.DonationRecipient'),
        ),
    ]
