# Generated by Django 3.0.5 on 2020-07-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0049_auto_20200722_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecipient',
            name='donation_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donationrecipient',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
