# Generated by Django 3.0.5 on 2020-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0050_auto_20200723_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecipient',
            name='donation_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donationrecipient',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
