# Generated by Django 3.0.5 on 2020-07-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0051_auto_20200723_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
    ]
