# Generated by Django 3.0.5 on 2020-09-05 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0053_auto_20200723_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='emissioninstance',
            name='fuel',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='carbontax.FuelType'),
        ),
    ]
