# Generated by Django 3.0.5 on 2020-09-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0054_auto_20200905_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioninstance',
            name='formatEncoding',
            field=models.IntegerField(default=0),
        ),
    ]
