# Generated by Django 3.0.5 on 2020-09-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0055_emissioninstance_formatencoding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissioninstance',
            old_name='formatEncoding',
            new_name='format_encoding',
        ),
    ]
