# Generated by Django 3.0.5 on 2020-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0056_auto_20200905_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioninstance',
            name='offset',
            field=models.FloatField(default=0),
        ),
    ]
