# Generated by Django 3.0.5 on 2020-09-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0058_auto_20200914_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='users', to='carbontax.DonationRecipient'),
        ),
    ]
