# Generated by Django 3.0.5 on 2020-09-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbontax', '0059_auto_20200914_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loc_lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='loc_lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
    ]
